// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WWGameplayTags
{

	//Input Tags
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_Targeting)
	
	//Player Tags
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Swords)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Pistols)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Rectifiers)

	//Event
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_WeaponEquip)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_WeaponUnEquip)

	//Ability
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dash)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump)

	//Status
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dashing)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Jumping)
};
