// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace GameplayTags
{
	//Input Tags
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hold)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_Targeting)
	
	//Player Tags
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Swords)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Pistols)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Rectifiers)

	//Event
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_WeaponEquip)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_WeaponUnEquip)

	//Ability
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Swords)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Pistols)
	WUTHERINGWAVES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Rectifiers)
	
};
